&copy;Copyright for [Shuang Wu] [2017]<br>
Cite from the [coursera] named [Neural network and Machine Learning] from [deeplearning.ai]<br>
Learning notes<br>

# Logistic Regression as a NN

## Binary Classification
* Binary Classification
    * lagel the img is cat (1) vs non-cat (0) (y)
        * img is in as red, green, blue intensities
        * each pixel is a value, e.g. $64*64$
        * x is just list all these pixeles in a single col.
        * x can also be $64*64*3=12288$
        * $n_x=12288$
        * want to predict $x\rightarrow y$
        ![img12](imgs/img12.jpg)
* Notation
    * $(x,y)$ single example
        * $x\in\mathbb{R}^{n_x}$
        * $y\in{0,1}$
    * m training example: {($x^1$, $y^1$), ($x^2$, $y^2$),$\cdots$,($x^m$, $y^m$)}
        * $m=m_{train}$
        * $m=m_{test}$
    * X = $[\vec{x^1}, \vec{x^2}, \cdots, \vec{x^m},]$
        * $X\in\mathbb{R}^{n_x*m}$
        * X.shape=($n_x$,m)
        ![img13](imgs/img13.jpg)
    * Y = [$y^1$, $y^2$, $\cdots$, $y^m$]
        * $Y\in\mathbb{R}^{1*m}$
        * Y.shape = (1,m)
        ![img14](imgs/img14.jpg)

## Logistic Reg.
* Logistic regression is a learning algorithm used in supervised learning problem
    * the output y are all 0 or 1
    * goal is to minimize the error b/w predictions and training data
* E.g.: Cat vs No-cat
    * Given an image represented by feature vector $x$
    * Probability of cat in img:
        * $Given\quad x, \hat{y}=P(y=1|x)\quad, where\quad0\leq\hat{y}\leq1$
    * Parameters in the logistic reg:
        * input fectures vecotr: $x\in\mathbb{R}^{n_x}$
        * training label: y
        * weights: $w\in\mathbb{R}^{n_x}$
        * threshold: $b\in\mathbb{R}$
        * output $\hat{y}=\sigma(w^Tx+b) = \sigma(z)$
        * sigmoid function: $s=\sigma(z)=\frac{1}{1+e^{-z}}$
        ![img15](imgs/img15.jpg)
        * $\sigma(w^Tx+b)$ is a linear function $(ax+b)$, but we are looking for prob. constraint b/w [0,1], so use sigmoid func.
        * Obs. from this graph
            * bounded b/w [0,1]
            * if z large positive, $\sigma(z)=1$
            * if z small negative, $\sigma(z)=0$
            * if $z=0$, $\sigma(z)=0.5$
* It's easy to use b and w separately instead of using the $\theta$

## Logistic Reg. Cost function

* Loss (error) function:
    * Measure the discrepancy b/t predication ($\hat{y}^{(i)}$) and desired output ($y^{(i)}$)
    * computes the error for single training example
    * $L(\hat{y}^{(i)}, y^{(i)}) = \frac{1}{2}(\hat{y}^{(i)}-y^{(i)})^2$
        * not convex so do not use this, because the GD will not find the global minimization
    * $L(\hat{y}^{(i)}, y^{(i)}) = -(y^{(i)}log(\hat{y}^{(i)}) + (1-y^{(i)})log(1-\hat{y}^{(i)}))$<br>
        * this will make the convex
    <br>
        * If $y^{(i)}=1$: $L(\hat{y}^{(i)}, y^{(i)})=-log(\hat{y}^{(i)})$ where $log(\hat{y}^{(i)})$ and $\hat{y}^{(i)}$ should be close to 1
        * If $y^{(i)}=0$: $L(\hat{y}^{(i)}, y^{(i)})=-log(1-\hat{y}^{(i)})$ where $log(1-\hat{y}^{(i)})$ and $\hat{y}^{(i)}$ should be close to 0<br>
        <br>
* Cost function
    * To train para. w and b
    * The average of the loss func. of the entire training set
    * want the para. w and b that <font color='red'>minimize</font> the overall cost func.
    $$J(w,b)=\frac{1}{m}\sum_{i=1}^mL(\hat{y}^{(i)}, y^{(i)})=-\frac{1}{m}\sum^m_{i=1}[(y^{(i)}log(\hat{y}^{(i)}) + (1-y^{(i)})log(1-\hat{y}^{(i)}))]$$

## Gradient descent

* GD
    * Convex
    ![img16](imgs/img16.jpg)
    * non-convec
    ![img17](imgs/img17.jpg)
    ![img18](imgs/img18.jpg)
    * initialize like the top red dot
    * then take step down hill in the direction
    * repeat the process until converge tor close to the global optimal
    * Process
        * repeat do {w:= w-$\alpha\frac{dJ(w)}{dw}$}
            * $\alpha$ is the learning rate
            * $w:=w-\alpha dw$
            * the derivative is the slope
        ![img18](imgs/img19.jpg)
        * $J(w, b)$ 
            * $w:=w-\alpha\frac{\partial J(w,b)}{\partial w}$
                * $w:=w-\alpha\partial w$
            * $b:=b-\alpha\frac{\partial J(w,b)}{\partial b}$
                * $b:=b-\alpha\partial b$
            * use $\partial$ when the function have at least two variable
        * 

## Derivatives

* Intuition
    * $f(a)=3a$
    ![img20](imgs/img20.jpg)
        * a=2, f(a)=6
            * a=2.001, f(a)=6.003
            * increase the $a$ by 0.001, same as increase the $f(a)$ by 0.003
            * slope (derivative) of $f(a)$ at $a=2$ is 3
            * slope os the height divided by the width
        * a=5, f(a)=15
            * a=5.001, f(a)=15.003
            * slope (derivative) of $f(a)$ at $a=5$ is 3
        * $\frac{df(a)}{da}=3=\frac{d}{da}f(a)$
        * stright line have the same slope everywhere

## More Derivatives

* Intuition
    * $f(a)=a^2$
    ![img21](imgs/img21.jpg)
        * a=2, f(a)=4
            * a = 2.001, $f(a)\approx 4.004$
            * slope (derivative) of f(a) at a=2 is 4
            * $\frac{d}{da}f(a)=4$ when a =2
        * a=5, f(a)=25
            * a =5.001, $f(a)\approx 25.010$
            * slope (derivative) of f(a) at a=5 is 10
            * $\frac{d}{da}f(a)=10$ when a =5
        * $\frac{d}{da}f(a)=\frac{d}{da}a^2=2a$
* more e.g.
    * $f(a)=a^3$
        * $\frac{d}{da}f(a)=3a^2$
    * $f(a)=log(a)$
        * $\frac{d}{da}f(a)=\frac{1}{a}$

## Computation graph

* J(a,b,c) = 3(a + bc)
    * u=bc
    * v =a + u
    * J = 3*v
    ![img22](imgs/img22.jpg)

## Derivatives w/ a computation graph

* one step back to calculate the derivative
* Chain rule
    * $\frac{dJ}{da}= \frac{dJ}{dv}\frac{dv}{da}$
    ![img23](imgs/img23.jpg)
* Final Output Var.
    * $\frac{d FOV}{d Var}$
        * "d var"
    ![img24](imgs/img24.jpg)

## Logistic Regression Gradient Descent

* ![img25](imgs/img25.jpg)

## GD on m Examples

* use for loop and then divided by m
* ![img26](imgs/img26.jpg)

# Python and vectorization

## Vectorization

* Vectorization
    * $z=w^Tx+b$
        * w and x are both vectors $\in\mathbb{R}^{n_x}$
* GPU and CPU
    * SIMD - single instantian multiple data


In [ ]:
# non-vec cal
z=0
for i in range(n):
    z+= w[i]*x[i]
    z+=b
    
## vec cal
z = np.dot(w,x) + b

In [1]:
import numpy as np
import time

a=np.array([1,2,3,4])

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc=time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic))+"ms")

c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop: " + str(1000*(toc-tic))+"ms")

250146.759712
Vectorized version: 131.99996948242188ms
250146.759712
For loop: 868.9999580383301ms


## More vectorization

* when possible, avoid for-loops
    * apply the exp. operation on every element of a matrix/vec.

In [2]:
# no-vec
u = np.zeros(n,1)
for i in range(n):
    u[i]=math.exp(v[i])
    
# vec
u = np.exp(v)

np.log(v)
np.abs(v)
np.maximum(v, 0)

NameError: name 'n' is not defined

## Vectorizing Logistic regression

* Broadcasting
* use vectorization to reduce the time

## Vec. logsitic regression gradient output



In [ ]:
# db=1/ m sum(dz(i))
1/m*(np.sum(dz))

#dw = 1/m Xdz.T
1/m*(np.sum(np.dot(X,dz)))

# w and b cal
z = np.dot(w.T, X)+b
A = simgma(z)
dz = A*Y
dw = 1/m*X*dZ.T
db=1/m*np.sum(dz)
w -= alpha*dw
b -= alpha*db


## Broadcasting in Python
![img27](imgs/img27.jpg)

In [4]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [5]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


## A note on python/numpy vec.

* do not use rank-one array

In [8]:
import numpy as np

a = np.random.randn(5)

print(a) # rank-1
print(a.shape)
print(a.T)
print(np.dot(a, a.T))

[ 1.70027017 -1.150852   -0.19721797  1.19697947 -3.11958897]
(5,)
[ 1.70027017 -1.150852   -0.19721797  1.19697947 -3.11958897]
15.4188691009


In [11]:
a = np.random.randn(5, 1)
print(a)
print(a.T)
print(np.dot(a, a.T))

[[-1.05841501]
 [ 0.98644671]
 [ 1.19374008]
 [ 0.30440944]
 [ 1.52607674]]
[[-1.05841501  0.98644671  1.19374008  0.30440944  1.52607674]]
[[ 1.12024233 -1.04407    -1.26347242 -0.32219152 -1.61522252]
 [-1.04407     0.97307711  1.17756098  0.30028369  1.50539338]
 [-1.26347242  1.17756098  1.42501538  0.36338575  1.82173897]
 [-0.32219152  0.30028369  0.36338575  0.09266511  0.46455217]
 [-1.61522252  1.50539338  1.82173897  0.46455217  2.32891021]]


## Quick tour of Jupyter/ipy nb

## Explanationof logistic regression cost func.

* if y=1: $p(y|x)=\hat{y}$
* if y=0: $p(y|x)=1-\hat{y}$
* $p(y|x) = \hat{y}^y(1-\hat{y})^{(1-y)}$

In [12]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [13]:
c.shape

(12288, 45)

In [14]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 